<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Slim 3</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-jsonview/1.2.3/jquery.jsonview.css" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.6/components/sidebar.min.css" />
  <style>
    html, body, #main, .embed-responsive, iframe {
      height: 100vh;
    }
    .embed-responsive{
      padding-bottom: 0; /* REMOVE SCROLL DOWN */
    }
    .menu-btn{
      width: 20px;
      height: 20px;
      background: red;
      position: absolute;
      top: 0;
      left: 0;
      z-index: 2;
    }
    .menu{
      background: white;
      display: flex;
      flex-direction: column;
    }
    .ui[class*="very wide"]{
      /*width: 100vw !important;*/
    }
    .span-title{
      font-weight: bold;
      color: black;
    }
    .side-header{
      order:1;
      height: 59px;
      position: absolute;
      background: black;
      z-index: 50;
    }
    .label {
      background: #e57373!important;
    }
    /*.input-search{
       width: 100%;
     }
     */
    .col-md-6{
      width: 100%;
    }
    .col-xs-4 {
      max-width: 200px;
    }
    .col-xs-4, .col-xs-8{
      padding-top: 10px;
      padding-bottom: 10px;
    }
    .col-xs-8 > p:nth-child(2), .span-title {
      display: inline;
    }
    .col-xs-8 > p:nth-child(4) {
      margin-bottom: 0;
      margin-top: 15px;
    }
    .btn-info{
      background-color: #f44336;
      border-color: #f44336;
      transition: all 0.3s ease-out;
    }
    .btn-info:hover {
      background-color: #d32f2f;
    }
    i{
      opacity: 0.8;
      transition: all 0.2s ease;
    }
    .btn-info:hover i{
      opacity: 1;
      transform: scale(1.1);
    }
    .btn{
      padding: 12px 12px;
    }
    #youtube-results > div:nth-child(1) > div > div.col-xs-8 > p:nth-child(4){}
    .youtube-action:nth-child(odd) {
      background: #eee;
    }
    .youtube-action:nth-child(even){
      background: #f5f5f5;
    }
    .side-content{
      /*background: blue;*/
      order:2;
      position: relative;
      overflow-x: hidden;
      overflow-y: scroll;
      height: 100%;
    }
    .side-content::-webkit-scrollbar{
      display:none;
    }
    .side-footer{
      /*background: red;*/
      order:3;
      position: relative;
      height: 80px;
      text-align: center;
    }
    .side-footer > button {
      background: none!important;
      font: inherit;
      font-size: 1.1em;
      border:none!important;
      padding: 20px 30px!important;
      color: #e91e63!important;
      transition: all 0.2s ease-out;
    }
    .side-footer > button:focus {
      outline: none!important;
    }
    .side-footer > button:active {
      font-size: 0.9em;
    }
    .side-footer > button:hover {
      transform: scale(1.1);
    }
    p > button {
      background: none!important;
      font: inherit;
      padding: 5px 30px!important;
      border: 2px solid #f44336!important;
      color: #e91e63!important;
      transition: all 0.3s ease-out;
    }
    p > button:focus {
      outline: none!important;
    }
    p > button:hover {
      color: white!important;
      background: #f44336!important;
    }
    p > button:active {
      transform: scale(0.9);
    }

    #search{
      border-radius: 0;
      opacity: 0;
      transition: opacity 0.3s ease-out;
    }
    #search:focus{
      opacity: 1;

    }
    #btn{
      border-radius: 0;
    }

  </style>
</head>
<body>

<aside class="ui bottom very wide vertical menu sidebar" style="height:500px!important;">
  <div class="side-content">
    <div id="youtube-results"></div>
  </div>
  <div class="side-footer">
    <button id="btn-next-youtube-results" class="hide">More Haikus ↓</button>
    <button id="btn-clear-youtube-results" >Clear Results</button>
  </div>
</aside>

<div class="side-header">
  <div class="row">
    <div class="col-md-6">
      <div class="input-group col-md-12">
        <input type="text" class="form-control input-lg input-search" id="search" placeholder = "Search" />
        <span class="input-group-btn">
        <button class="btn btn-info btn-lg, btn-search" id="btn" type="button">
          <i class="glyphicon glyphicon-search"></i>
      </div>
    </div>
  </div>
  <!--<button type="button" class="btn-search" style="display: none" id="btn">search</button>-->
</div>


<main id="main" class="pusher">
  <div class="embed-responsive embed-responsive-16by9">
    <div id="player"></div>
  </div>
</main>
<!--<div class="menu-btn">-->
</div>
<div id="partials" class="hide">
  <div class="youtube-action container-fluid">
    <div class="row">
      <div class="col-xs-4">
        <img src="" class="img-thumb img-responsive"/>
      </div>
      <div class="col-xs-8">
        <p class="span-title"> some title</p>
        <p><span class="span-time label label-default">0</span> </p>
        <p>
          <a target="_blank" class="span-descr">some channel</a>
        </p>
        <p>
          <button class="btn btn-default btn-play" type="button" data-id=""> Watch </button>
        </p>
      </div>
    </div>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.2/lodash.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.6/components/sidebar.js"></script>

<script>
  playerStatus = 0;
  $('#btn').on('mouseover', function(){
    $("#search").focus();
  });
  $("#search").keyup(function(event){
    if(event.keyCode == 13){
      $("#btn").click();
    }
  });

  $('.ui.sidebar').sidebar({
    transition: 'scale down',
    onVisible: function(){
    },
    onHide: function(){
      if(playerStatus === 2){
      player.playVideo();
      }
    }
  });
  $(document).on('click', '.btn-search',function(){
    $('.ui.sidebar')
      .sidebar('show');
    clearAll();
  });
  var videosArray= [];
  var searchForString = "";
  $(document).on('click','.btn-search'  , searchInputVideo);
  $(document).on('click','.btn-play'    , playVideo);
  $(document).on('click','#btn-next-youtube-results' , nextPageBtn);
  $(document).on('click','#btn-clear-youtube-results' , clearAll);
  function clearAll(){
    $('#youtube-results').html('');
    videosArray = [];
  }
  function playVideo(){
    var code = $(this).attr('data-id');
    done = false;
    $('.ui.sidebar')
      .sidebar('toggle');
    player.loadVideoById(code);
  }
  function searchInputVideo(e){
//    videosArray = [];
    searchVideo( $('.input-search').val());
    $('.input-search').val('');
  }
  function searchVideo(search){
    searchForString = search;
    var request  = $.ajax({
      url: './api/youtube/search',
      data: { q: searchForString }
    });
    request.done(function (data, textStatus, jqXHR ) {
      renderVideoList(data.items);
      setNextPageButton(data.nextPageToken);
    });
    request.fail(function (jqXHR, textStatus, errorThrown) {

    });
    request.always(function( data, textStatus, jqXHR ) {

    });
  }
  function searchVideoNextPage(pageId){
    var request  = $.ajax({
      url: './api/youtube/search/page',
      data: {
        pageToken: pageId,
        q: searchForString
      }
    });
    request.done(function (data, textStatus, jqXHR ) {
      renderVideoList(data.items);
      setNextPageButton(data.nextPageToken);
    });
    request.fail(function (jqXHR, textStatus, errorThrown) {

    });
    request.always(function( data, textStatus, jqXHR ) {

    });
  }
  function searchVideoInfo(videoId,$objView){
    var request  = $.ajax({
      url: './api/youtube/search/video',
      data: {
        ids: videoId,
      }
    });
    request.done(function (data, textStatus, jqXHR ) {
      var reptms = /^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/;
      var hours = 0, minutes = 0, seconds = 0, totalseconds;
      if (reptms.test(data.items[0].contentDetails.duration)) {
        var matches = reptms.exec(data.items[0].contentDetails.duration);
        if (matches[1]) hours = Number(matches[1]);
        if (matches[2]) minutes = Number(matches[2]);
        if (matches[3]) seconds = Number(matches[3]);
        totalseconds = hours * 3600  + minutes * 60 + seconds;
        if(totalseconds>20){
          _.remove(videosArray, function(o) { return o.id.videoId == videoId; });
        }else{
          var $partial = $('#partials .youtube-action').clone();
          $partial.find('button').attr('data-id',data.items[0].id);
          $partial.find('.span-title').html(data.items[0].snippet.title);
          $partial.find('.span-descr').html(data.items[0].snippet.channelTitle);
          $partial.find('.span-descr').attr('href', "//youtube.com/channel/"+data.items[0].snippet.channelId);
          $partial.find('.img-thumb').attr('src',data.items[0].snippet.thumbnails.high.url);
          $partial.find('.span-time').html(totalseconds + " sec");
          $('#youtube-results').append($partial);
        }
      }

    });
    request.fail(function (jqXHR, textStatus, errorThrown) {

    });
    request.always(function( data, textStatus, jqXHR ) {

    });
  }

  function nextPageBtn(e){
    searchVideoNextPage($(this).attr('data-id'));
  }


  function setNextPageButton(pageHash){
    $('#btn-next-youtube-results').attr('data-id', pageHash);
    $('#btn-next-youtube-results').removeClass('hide');

  }

  function renderVideoList(items){
    if(items.length > 0){
//      $('#btn-next-youtube-results').removeClass('hidden');
      for(item in items){

        var o = _.find(videosArray, function(o) { return o.id.videoId == items[item].id.videoId; })
        if(o == undefined ){
          videosArray.push(items[item]);
          searchVideoInfo(items[item].id.videoId,null);
        }
      }
//      $('#btn-next-youtube-results').trigger('click');
    }else{
      $('#btn-next-youtube-results').addClass('hidden');
    }
  }


  // 2. This code loads the IFrame Player API code asynchronously.
  var tag = document.createElement('script');
  tag.src = "https://www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  // 3. This function creates an <iframe> (and YouTube player)
  //    after the API code downloads.
  var player;
  function onYouTubeIframeAPIReady() {
    player = new YT.Player('player', {
      videoId : 'XjrC_jv7xHA',
      playerVars: {
        'color': 'white', 'autoplay': 0, 'controls': 1, 'rel': 0, 'showinfo': 0
      },
      events: {
        'onReady': onPlayerReady,
        'onStateChange': onPlayerStateChange
      }
    });
  }
  // 4. The API will call this function when the video player is ready.
  function onPlayerReady(event) {
  }

  // 5. The API calls this function when the player's state changes.
  function onPlayerStateChange(event) {
    playerStatus = event.data;
    if(event.data === 0 || event.data === 2 ){
      if($('#youtube-results').children().length>0){
        $('.ui.sidebar').sidebar('show');
      }else{
        $('#search').focus();
      }
    }
  }
</script>
</body>
</html>
