<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Slim 3</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-jsonview/1.2.3/jquery.jsonview.css" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <style>
  </style>
</head>
<body>
<div class="container-fluid">
  <div class="text-center">
    <div id="player"></div>
    <div id="search">
      <input type="text" class="input-search " /> <button type="button" class="btn-search ">search</button>
    </div>
  </div>
  <div id="results">
    <pre></pre>
    <div id="youtube-results" class="row"></div>
    <div >
      <button id="btn-next-youtube-results" class="btn btn-primary">NEXT PAGE</button>
    </div>
  </div>
  <div id="partials" class="hide">
    <div class="youtube-action col-md-4 col-sm-6">
      <div class="thumbnail">
        <img src="" class="img-thumb img-responsive"/>
        <div class="caption">
          <p class="span-title"> some title</p>
          <p><span class="span-time label label-default">0</span> </p>
          <p>
            <button class="btn btn-default btn-play" type="button" data-id=""> play </button>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-jsonview/1.2.3/jquery.jsonview.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script>
  var searchForString = "";
  $(function(){
    searchVideo('humber');
  });

  $(document).on('click','.btn-search'  , searchInputVideo);
  $(document).on('click','.btn-play'    , playVideo);
  $(document).on('click','#btn-next-youtube-results',nextPageBtn)
  function playVideo(){
    var code = $(this).attr('data-id');
    console.log(code);
    done = false;
    player.loadVideoById(code);
  }
  function searchInputVideo(e){
    searchVideo( $('.input-search').val());
    $('.input-search').val('');
  }
  function searchVideo(search){
    searchForString = search;
    var request  = $.ajax({
      url: './api/youtube/search',
      data: { q: searchForString }
    });
    request.done(function (data, textStatus, jqXHR ) {
      $('#results pre').JSONView(data, { collapsed: true });
      $('#youtube-results').html('');
      renderVideoList(data.items);
      setNextPageButton(data.nextPageToken);
    });
    request.fail(function (jqXHR, textStatus, errorThrown) {

    });
    request.always(function( data, textStatus, jqXHR ) {

    });
  }

  function searchVideoNextPage(pageId){
    var request  = $.ajax({
      url: './api/youtube/search/page',
      data: {
        pageToken: pageId,
        q: searchForString
      }
    });
    request.done(function (data, textStatus, jqXHR ) {
      $('#results pre').JSONView(data, { collapsed: true });
      renderVideoList(data.items);
      setNextPageButton(data.nextPageToken);
    });
    request.fail(function (jqXHR, textStatus, errorThrown) {

    });
    request.always(function( data, textStatus, jqXHR ) {

    });
  }
  function searchVideoInfo(videoId,$objView){
    var request  = $.ajax({
      url: './api/youtube/search/video',
      data: {
        ids: videoId,
      }
    });
    request.done(function (data, textStatus, jqXHR ) {
      $('#results pre').JSONView(data, { collapsed: true });
      var reptms = /^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/;
      var hours = 0, minutes = 0, seconds = 0, totalseconds;

      if (reptms.test(data.items[0].contentDetails.duration)) {
        var matches = reptms.exec(data.items[0].contentDetails.duration);
        if (matches[1]) hours = Number(matches[1]);
        if (matches[2]) minutes = Number(matches[2]);
        if (matches[3]) seconds = Number(matches[3]);
        totalseconds = hours * 3600  + minutes * 60 + seconds;
        $objView.find('.span-time').html(totalseconds + " sec");
        if(totalseconds>20){
          $objView.remove();
        }
      }

    });
    request.fail(function (jqXHR, textStatus, errorThrown) {

    });
    request.always(function( data, textStatus, jqXHR ) {

    });
  }

  function nextPageBtn(e){
    searchVideoNextPage($(this).attr('data-id'));
  }


  function setNextPageButton(pageHash){
    $('#btn-next-youtube-results').attr('data-id', pageHash);
    $('#btn-next-youtube-results').removeClass('hide');

  }

  function renderVideoList(items){
    console.log(items.length);
    if(items.length > 0){
      $('#btn-next-youtube-results').removeClass('hidden');
    console.log("here");
      for(item in items){
        var $partial = $('#partials .youtube-action').clone();
        $partial.find('button').attr('data-id',items[item].id.videoId);
        $partial.find('.span-title').html(items[item].snippet.title);
        $partial.find('.img-thumb').attr('src',items[item].snippet.thumbnails.high.url);
        $('#youtube-results').append($partial);
        searchVideoInfo(items[item].id.videoId,$partial);
      }
      $('#btn-next-youtube-results').trigger('click');
    }else{
    console.log("there");
      $('#btn-next-youtube-results').addClass('hidden');
    }
  }


  // 2. This code loads the IFrame Player API code asynchronously.
  var tag = document.createElement('script');
  tag.src = "https://www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  // 3. This function creates an <iframe> (and YouTube player)
  //    after the API code downloads.
  var player;
  function onYouTubeIframeAPIReady() {
    player = new YT.Player('player', {
      height: '390',
      width: '640',
      events: {
        'onReady': onPlayerReady,
        'onStateChange': onPlayerStateChange
      }
    });
  }

  // 4. The API will call this function when the video player is ready.
  function onPlayerReady(event) {
    event.target.playVideo();
  }

  // 5. The API calls this function when the player's state changes.
  function onPlayerStateChange(event) {
  }
</script>
</body>
</html>
